-- =========================================================================
-- MIGRATION 020: Journal controls.
-- 1. Unique reference number enforced per organisation on manual journals.
-- 2. System source types (payment, loan_disbursement, loan_repayment,
--    contribution) are flagged as read-only — the UI uses this, and the
--    fn_add_journal_line function blocks adding lines to posted entries.
-- Run after 001-019. Safe to re-run.
-- =========================================================================

-- Block manual line additions to SYSTEM-generated journal entries
-- (those whose source_type is not 'manual' or 'reallocation').
create or replace function fn_add_journal_line(
  p_entry_id   uuid,
  p_account_id uuid,
  p_debit      numeric,
  p_credit     numeric,
  p_member_id  uuid default null
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_org    uuid;
  v_stat   journal_status;
  v_source text;
  v_id     uuid;
begin
  select organisation_id, status, source_type
    into v_org, v_stat, v_source
    from journal_entries where id = p_entry_id;

  if v_stat = 'posted' then
    raise exception 'Cannot add lines to a posted journal. Use a reversal/correction instead.';
  end if;
  if v_source not in ('manual','reallocation') then
    raise exception 'This journal entry was generated by the system (%). Manual line additions are not permitted.', v_source;
  end if;
  if not has_org_role(v_org, array['org_admin','treasurer','accountant']::org_role[]) then
    raise exception 'Not authorised';
  end if;
  if coalesce(p_debit,0) > 0 and coalesce(p_credit,0) > 0 then
    raise exception 'A journal line cannot have both a debit and a credit value.';
  end if;
  if coalesce(p_debit,0) = 0 and coalesce(p_credit,0) = 0 then
    raise exception 'A journal line must have a non-zero debit or credit.';
  end if;

  insert into journal_lines(journal_entry_id, account_id, debit, credit, member_id)
  values (p_entry_id, p_account_id, coalesce(p_debit,0), coalesce(p_credit,0), p_member_id)
  returning id into v_id;
  return v_id;
end;
$$;

-- Enforce unique reference per organisation on manual entries.
-- We add a partial unique index (only on manual entries with a reference).
create unique index if not exists uq_manual_journal_reference
  on journal_entries(organisation_id, source_type, journal_number)
  where source_type = 'manual' and journal_number is not null;

-- Update fn_create_draft_journal to require a description and allow
-- an optional reference that must not clash with existing ones.
create or replace function fn_create_draft_journal(
  p_organisation_id uuid,
  p_entry_date      date,
  p_description     text,
  p_reference       text default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id  uuid;
  v_num text;
begin
  if not has_org_role(p_organisation_id, array['org_admin','treasurer','accountant']::org_role[]) then
    raise exception 'Not authorised to create journal entries';
  end if;
  if p_description is null or trim(p_description) = '' then
    raise exception 'A description is required for all journal entries';
  end if;

  v_num := fn_next_journal_number(p_organisation_id);

  insert into journal_entries(organisation_id, entry_date, description,
    source_type, status, journal_number, created_by)
  values (p_organisation_id, p_entry_date, p_description,
    'manual', 'draft', v_num, auth.uid())
  returning id into v_id;

  return jsonb_build_object('id', v_id, 'journal_number', v_num);
end;
$$;
